### ISSUE TITLE
ResourceWarning about unclosed /dev/null with unittest

### ISSUE THREAD

**Issue by jesaerys** [bartdag/py4j#264] opened 2016-11-21 20:37 UTC
I keep seeing `ResourceWarning`s when I run unit tests that set up a Java gateway. Below is a minimal example.

Create the file test.py:
```python
import unittest
import py4j.java_gateway

def hello():
    gateway = py4j.java_gateway.JavaGateway.launch_gateway(die_on_exit=True)
    try:
        return gateway.jvm.java.lang.String('Hello world')
    finally:
        gateway.shutdown()

class TestHello(unittest.TestCase):

    def test_hello(self):
        message = hello()
        self.assertEqual(message, 'Hello world')

if __name__ == '__main__':
    unittest.main()
```

Now run it:
```console
$ python test.py
/Users/.../python3.5/site-packages/py4j/java_gateway.py:1952: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
  create_new_process_group=create_new_process_group)
.
----------------------------------------------------------------------
Ran 1 test in 0.163s

OK
$ 
```

As far as I can tell this is related to the opening of `/dev/null` for stdout/stderr in `java_gateway.py`. I suppose these handles should be explicitly closed at some point?

**Comment by bartdag** [comment] 2016-11-21 21:05
Thanks for reporting this issue. It seems this is a warning specifically printed by Python 3.5 (Python 3.4 and 2.x does not print this at all).

I'll see what I can do, but currently, the consumer thread that explicitly closes /dev/null is a daemon thread that may not fully execute before the python process exits and Python is supposed to correctly close opened files (probably after the warning is printed though) on exit.

**Comment by bartdag** [comment] 2016-11-22 10:15
I'm almost done with a simple fix. I'm trying to find in Python 3.5 changelog what can explain this new warning, because it seems to popup only when Popen takes a file descriptor and the method returns without closing it: even if the file descriptor is closed in another method, the warning is emitted, which is very annoying.

I also learned a way to temporarily ignore warnings if this ever happens in the future:

```python
import warnings

def test_hello(self):
   with warnings.catch_warnings():
       warnings.simplefilter("ignore")
       message = hello()
       self.assertEqual(message, 'Hello world')
```

**Closed** 2016-11-22 11:05 UTC

**Comment by jesaerys** [comment] 2016-11-22 17:38
Thanks @bartdag. I read somewhere that `ResourceWarning` filtered by default under most circumstances, and that the filter is lifted for unittest. Now I'm trying to remember where I read that... it might help indicate why this issue is specific to 3.5.

Either way, I agree that the `warnings` module provides a handy remedy. Here is what I've added to my test case to target the exact warning:

```python
with warnings.catch_warnings():
    warnings.filterwarnings(
        'ignore',
        message='unclosed file.*name=\'/dev/null\'',
        category=ResourceWarning,
        module='py4j.java_gateway',
        lineno=1952)
    ...
```

**Comment by bartdag** [comment] 2016-11-23 08:41
Lifting the warning filter for unit test would explain why I could not reproduce the warning outside a unit test! Thanks for the tip! Still couldn't find anything in the changelog. In any case, the code in the master branch should no longer emit a warning.

**Comment by jesaerys** [comment] 2016-11-23 20:38
Thanks for your effort!
