### ISSUE TITLE
Passing integer values larger than Long.MAX_VALUE to Java causes error and leaves gateway in bad state

### ISSUE THREAD

**Issue by JoshRosen** [bartdag/py4j#265] opened 2016-12-31 22:38 UTC
While using [Hypothesis](http://hypothesis.works) to test Spark, I discovered an interesting bug in Py4j related to passing Python integers that are bigger than Long.MAX_VALUE to Java. This not only results in an error but causes the immediately following command to the gateway to fail.

Here's a minimal reproduction. First, setup a new Java gateway:

```python
from py4j.java_gateway import launch_gateway, GatewayClient, JavaGateway
gateway_port = launch_gateway()
client = GatewayClient(port=gateway_port)
gateway = JavaGateway(client)
```

Establish that it's in working order by using Long.MAX_VALUE:

```
>>> gateway.jvm.java.lang.Math.abs(9223372036854775807L)
9223372036854775807L
```

Try a number that's bigger than the maximum and note that it fails:

```
>>> gateway.jvm.java.lang.Math.abs(9223372036854775807L + 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joshrosen/anaconda/envs/env/lib/python2.7/site-packages/py4j-0.10.4-py2.7.egg/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/joshrosen/anaconda/envs/env/lib/python2.7/site-packages/py4j-0.10.4-py2.7.egg/py4j/protocol.py", line 323, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling z:java.lang.Math.abs. Trace:
java.lang.NumberFormatException: For input string: "9223372036854775808"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:596)
	at java.lang.Long.parseLong(Long.java:631)
	at py4j.Protocol.getLong(Protocol.java:234)
	at py4j.Protocol.getObject(Protocol.java:286)
	at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:82)
	at py4j.commands.CallCommand.execute(CallCommand.java:77)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

Next, and this is the more serious bug as far as I'm concerned, try to run another command and observe that the previous failure left the system in a bad state:

```
>>> gateway.jvm.java.lang.Math.abs(123L)
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/Users/joshrosen/anaconda/envs/env/lib/python2.7/site-packages/py4j-0.10.4-py2.7.egg/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/Users/joshrosen/anaconda/envs/env/lib/python2.7/site-packages/py4j-0.10.4-py2.7.egg/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joshrosen/anaconda/envs/env/lib/python2.7/site-packages/py4j-0.10.4-py2.7.egg/py4j/java_gateway.py", line 1532, in __getattr__
    raise Py4JError("{0} does not exist in the JVM".format(name))
py4j.protocol.Py4JError: java does not exist in the JVM
```

If you turn around and try this again, though, the bad state will have been cleared and things work again:

```
>>> gateway.jvm.java.lang.Math.abs(123L)
123L
```

**Comment by bartdag** [comment] 2017-01-11 11:08
Thanks for reporting this bug. I agree that the second issue (bad state after exception is thrown) is a problematic. I'll see what I can do and fix it in the 0.11 and 0.10 branch.

**Comment by bartdag** [comment] 2017-01-15 21:13
This bug is probably a regression introduced by #220 because network failure on "receive" no longer result in an automated retry.

This is what happens on the Java side:

1. Try to decode an argument
2. Raises a runtime exception
3. Runtime exception is caught, a proper error message is sent back to the Python side, the connection is closed on the Java side because connection state may be inconsistent (we don't know why an exception occurs).

On the Python side, there is no way to know that the connection was closed after an error message was sent. So the second time gateway.jvm.java.lang.Math.abs(123L) is called, the python side will:

1. Send a message through the same connection as the previous one.
2. While waiting to receive a message, a network error will be raised because Java previously closed the connection.
3. Because the network error occurred while receiving, nothing is done, and the exception is just propagated.

What I did is change a little bit the network code so that when Java closes the connection, it uses SO_LINGER so Python will know when sending the message that the connection was reset. This is the strategy I used to automatically retry to send a message when a connection expired. I also ported the fix to the callback server and the ClientServer code.

This means that a call to abs with 9223372036854775807L + 1 will fail, but subsequent calls should no longer fail.

I'll have to write a test though for this specific error (overflowing long) and port the fix to the binary protocol branch.

**Comment by bartdag** [comment] 2017-01-16 11:38
Unfortunately, my fix works on MacOSX but does not seem to work on Linux so this is still unfixed for now.

Internal notes:
- Could tell the Python side to close the connection explicitly. Probably the best solution, but considering that the protocol is changing in 0.11.x, that seems a lot of work for the current branch.
- Need to debug why the SO_LINGER solution does not work on Linux.
- There is also the problem if the Python side is sending a lot of data (multiple network writes) and Java chokes in the middle. I don't think the protocol is ready to handle large bad data anyway. Closing the connection is again the best thing that could happen.
- Could just fix this issue by bound checking long input for now. But this could probably happen with badly formatted strings too so better have a good fix for this.
- Can we infer when to close the connection? Probably hard for now (e.g., method does not exist raises the same exception as bad LONG input). Need to be explicit...

**Comment by bartdag** [comment] 2017-01-18 10:42
Internal notes: I fixed the problem by explicitly sending a "FATAL ERROR" that tells the Python side to close the connection. This passes all tests on linux and macosx and does not rely on socket programming at all. I now need to port this to the callback server side, although such errors are much less likely considering that Java is strongly typed.

There is still the possible issue with very large arguments (e.g., a bad long argument passed between large byte arrays) might break the connection in a unrecoverable way. The binary protocol will be better suited to handle such case (because an overflowing long should not convert with pack), but that will still need to be addressed specifically by sending to the other side some kind of STOP COMMAND (telling the other side that an error occurred while sending the argument and to disregard the current command).

**Closed** 2017-05-23 12:21 UTC
Labels: bug
